export const all_countries = [
  {
    country: "Afghanistan",
    phone_code: "93",
    currency: "Afghan Afghani",
    currency_bn: "আফগানি",
    currency_code: "AFN",
    currency_symbol: "؋",
    flag_code: "AF",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AF.svg",
    timezone: "UTC+04:30",
    named_timezone: "Asia/Kabul",
  },
  {
    country: "Albania",
    phone_code: "355",
    currency: "Albanian Lek",
    currency_bn: "আলবেনিয়ান লেক",
    currency_code: "ALL",
    currency_symbol: "L",
    flag_code: "AL",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AL.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Tirane",
  },
  {
    country: "Algeria",
    phone_code: "213",
    currency: "Algerian Dinar",
    currency_bn: "আলজেরিয়ান দিনার",
    currency_code: "DZD",
    currency_symbol: "د.ج",
    flag_code: "DZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/DZ.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Algiers",
  },
  {
    country: "Andorra",
    phone_code: "376",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "AD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AD.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Andorra",
  },
  {
    country: "Angola",
    phone_code: "244",
    currency: "Angolan Kwanza",
    currency_bn: "অ্যাঙ্গোলান কোয়ানজা",
    currency_code: "AOA",
    currency_symbol: "Kz",
    flag_code: "AO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AO.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Luanda",
  },
  {
    country: "Argentina",
    phone_code: "54",
    currency: "Argentine Peso",
    currency_bn: "আর্জেন্টাইন পেসো",
    currency_code: "ARS",
    currency_symbol: "$",
    flag_code: "AR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AR.svg",
    timezone: "UTC−03:00",
    named_timezone: "America/Argentina/Buenos_Aires",
  },
  {
    country: "Armenia",
    phone_code: "374",
    currency: "Armenian Dram",
    currency_bn: "আর্মেনিয়ান দ্রাম",
    currency_code: "AMD",
    currency_symbol: "֏",
    flag_code: "AM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AM.svg",
    timezone: "UTC+04:00",
    named_timezone: "Asia/Yerevan",
  },
  {
    country: "Australia",
    phone_code: "61",
    currency: "Australian Dollar",
    currency_bn: "অস্ট্রেলিয়ান ডলার",
    currency_code: "AUD",
    currency_symbol: "$",
    flag_code: "AU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AU.svg",
    timezone: "UTC+10:00",
    named_timezone: "Australia/Sydney",
  },
  {
    country: "Austria",
    phone_code: "43",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "AT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AT.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Vienna",
  },
  {
    country: "Azerbaijan",
    phone_code: "994",
    currency: "Azerbaijani Manat",
    currency_bn: "আজারবাইজানি মানাত",
    currency_code: "AZN",
    currency_symbol: "₼",
    flag_code: "AZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AZ.svg",
    timezone: "UTC+04:00",
    named_timezone: "Asia/Baku",
  },
  {
    country: "Bahamas",
    phone_code: "1-242",
    currency: "Bahamian Dollar",
    currency_bn: "বাহামিয়ান ডলার",
    currency_code: "BSD",
    currency_symbol: "$",
    flag_code: "BS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BS.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Nassau",
  },
  {
    country: "Bahrain",
    phone_code: "973",
    currency: "Bahraini Dinar",
    currency_bn: "বাহরাইনি দিনার",
    currency_code: "BHD",
    currency_symbol: ".د.ب",
    flag_code: "BH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BH.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Bahrain",
  },
  {
    country: "Bangladesh",
    phone_code: "88",
    currency: "Bangladeshi Taka",
    currency_bn: "বাংলাদেশি টাকা",
    currency_code: "BDT",
    currency_symbol: "৳",
    flag_code: "BD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BD.svg",
    timezone: "UTC+06:00",
    named_timezone: "Asia/Dhaka",
  },
  {
    country: "Barbados",
    phone_code: "1-246",
    currency: "Barbadian Dollar",
    currency_bn: "বার্বাডিয়ান ডলার",
    currency_code: "BBD",
    currency_symbol: "$",
    flag_code: "BB",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BB.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Barbados",
  },
  {
    country: "Belarus",
    phone_code: "375",
    currency: "Belarusian Ruble",
    currency_bn: "বেলারুশিয়ান রুবেল",
    currency_code: "BYN",
    currency_symbol: "Br",
    flag_code: "BY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BY.svg",
    timezone: "UTC+03:00",
    named_timezone: "Europe/Minsk",
  },
  {
    country: "Belgium",
    phone_code: "32",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "BE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BE.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Brussels",
  },
  {
    country: "Belize",
    phone_code: "501",
    currency: "Belize Dollar",
    currency_bn: "বেলিজ ডলার",
    currency_code: "BZD",
    currency_symbol: "$",
    flag_code: "BZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BZ.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/Belize",
  },
  {
    country: "Benin",
    phone_code: "229",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "BJ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BJ.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Porto-Novo",
  },
  {
    country: "Bhutan",
    phone_code: "975",
    currency: "Bhutanese Ngultrum",
    currency_bn: "ভুটানি নুলট্রাম",
    currency_code: "BTN",
    currency_symbol: "Nu.",
    flag_code: "BT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BT.svg",
    timezone: "UTC+06:00",
    named_timezone: "Asia/Thimphu",
  },
  {
    country: "Bolivia",
    phone_code: "591",
    currency: "Bolivian Boliviano",
    currency_bn: "বলিভিয়ান বলিভিয়ানো",
    currency_code: "BOB",
    currency_symbol: "Bs.",
    flag_code: "BO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BO.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/La_Paz",
  },
  {
    country: "Bosnia and Herzegovina",
    phone_code: "387",
    currency: "Bosnia and Herzegovina Convertible Mark",
    currency_bn: "বসনিয়া ও হার্জেগোভিনা কনভার্টিবল মার্ক",
    currency_code: "BAM",
    currency_symbol: "KM",
    flag_code: "BA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BA.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Sarajevo",
  },
  {
    country: "Botswana",
    phone_code: "267",
    currency: "Botswana Pula",
    currency_bn: "বতসোয়ানা পুলা",
    currency_code: "BWP",
    currency_symbol: "P",
    flag_code: "BW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BW.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Gaborone",
  },
  {
    country: "Brazil",
    phone_code: "55",
    currency: "Brazilian Real",
    currency_bn: "ব্রাজিলিয়ান রিয়াল",
    currency_code: "BRL",
    currency_symbol: "R$",
    flag_code: "BR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BR.svg",
    timezone: "UTC−03:00",
    named_timezone: "America/Sao_Paulo",
  },
  {
    country: "Brunei",
    phone_code: "673",
    currency: "Brunei Dollar",
    currency_bn: "ব্রুনাই ডলার",
    currency_code: "BND",
    currency_symbol: "$",
    flag_code: "BN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BN.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Brunei",
  },
  {
    country: "Bulgaria",
    phone_code: "359",
    currency: "Bulgarian Lev",
    currency_bn: "বুলগেরিয়ান লেভ",
    currency_code: "BGN",
    currency_symbol: "лв",
    flag_code: "BG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BG.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Sofia",
  },
  {
    country: "Burkina Faso",
    phone_code: "226",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "BF",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BF.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Ouagadougou",
  },
  {
    country: "Burundi",
    phone_code: "257",
    currency: "Burundian Franc",
    currency_bn: "বুরুন্ডিয়ান ফ্রাঙ্ক",
    currency_code: "BIF",
    currency_symbol: "Fr",
    flag_code: "BI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/BI.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Bujumbura",
  },
  {
    country: "Cambodia",
    phone_code: "855",
    currency: "Cambodian Riel",
    currency_bn: "কম্বোডিয়ান রিয়েল",
    currency_code: "KHR",
    currency_symbol: "៛",
    flag_code: "KH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KH.svg",
    timezone: "UTC+07:00",
    named_timezone: "Asia/Phnom_Penh",
  },
  {
    country: "Cameroon",
    phone_code: "237",
    currency: "Central African CFA Franc",
    currency_bn: "মধ্য আফ্রিকান সিএফএ ফ্রাঙ্ক",
    currency_code: "XAF",
    currency_symbol: "Fr",
    flag_code: "CM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CM.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Douala",
  },
  {
    country: "Canada",
    phone_code: "1",
    currency: "Canadian Dollar",
    currency_bn: "কানাডিয়ান ডলার",
    currency_code: "CAD",
    currency_symbol: "$",
    flag_code: "CA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CA.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Toronto",
  },
  {
    country: "Cape Verde",
    phone_code: "238",
    currency: "Cape Verdean Escudo",
    currency_bn: "কেপ ভার্দিয়ান এসকুডো",
    currency_code: "CVE",
    currency_symbol: "$",
    flag_code: "CV",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CV.svg",
    timezone: "UTC−01:00",
    named_timezone: "Atlantic/Cape_Verde",
  },
  {
    country: "Central African Republic",
    phone_code: "236",
    currency: "Central African CFA Franc",
    currency_bn: "মধ্য আফ্রিকান সিএফএ ফ্রাঙ্ক",
    currency_code: "XAF",
    currency_symbol: "Fr",
    flag_code: "CF",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CF.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Bangui",
  },
  {
    country: "Chad",
    phone_code: "235",
    currency: "Central African CFA Franc",
    currency_bn: "মধ্য আফ্রিকান সিএফএ ফ্রাঙ্ক",
    currency_code: "XAF",
    currency_symbol: "Fr",
    flag_code: "TD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TD.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Ndjamena",
  },
  {
    country: "Chile",
    phone_code: "56",
    currency: "Chilean Peso",
    currency_bn: "চিলিয়ান পেসো",
    currency_code: "CLP",
    currency_symbol: "$",
    flag_code: "CL",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CL.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Santiago",
  },
  {
    country: "China",
    phone_code: "86",
    currency: "Chinese Yuan",
    currency_bn: "চীনা ইউয়ান",
    currency_code: "CNY",
    currency_symbol: "¥",
    flag_code: "CN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CN.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Shanghai",
  },
  {
    country: "Colombia",
    phone_code: "57",
    currency: "Colombian Peso",
    currency_bn: "কলম্বিয়ান পেসো",
    currency_code: "COP",
    currency_symbol: "$",
    flag_code: "CO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CO.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Bogota",
  },
  {
    country: "Comoros",
    phone_code: "269",
    currency: "Comorian Franc",
    currency_bn: "কোমোরিয়ান ফ্রাঙ্ক",
    currency_code: "KMF",
    currency_symbol: "Fr",
    flag_code: "KM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KM.svg",
    timezone: "UTC+03:00",
    named_timezone: "Indian/Comoro",
  },
  {
    country: "Congo",
    phone_code: "242",
    currency: "Central African CFA Franc",
    currency_bn: "মধ্য আফ্রিকান সিএফএ ফ্রাঙ্ক",
    currency_code: "XAF",
    currency_symbol: "Fr",
    flag_code: "CG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CG.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Brazzaville",
  },
  {
    country: "Costa Rica",
    phone_code: "506",
    currency: "Costa Rican Colón",
    currency_bn: "কোস্টা রিকান কোলন",
    currency_code: "CRC",
    currency_symbol: "₡",
    flag_code: "CR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CR.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/Costa_Rica",
  },
  {
    country: "Croatia",
    phone_code: "385",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "HR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/HR.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Zagreb",
  },
  {
    country: "Cuba",
    phone_code: "53",
    currency: "Cuban Peso",
    currency_bn: "কিউবান পেসো",
    currency_code: "CUP",
    currency_symbol: "$",
    flag_code: "CU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CU.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Havana",
  },
  {
    country: "Cyprus",
    phone_code: "357",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "CY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CY.svg",
    timezone: "UTC+02:00",
    named_timezone: "Asia/Nicosia",
  },
  {
    country: "Czech Republic",
    phone_code: "420",
    currency: "Czech Koruna",
    currency_bn: "চেক করুনা",
    currency_code: "CZK",
    currency_symbol: "Kč",
    flag_code: "CZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CZ.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Prague",
  },
  {
    country: "Denmark",
    phone_code: "45",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "DK",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/DK.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Copenhagen",
  },
  {
    country: "Djibouti",
    phone_code: "253",
    currency: "Djiboutian Franc",
    currency_bn: "জিবুতিয়ান ফ্রাঙ্ক",
    currency_code: "DJF",
    currency_symbol: "Fr",
    flag_code: "DJ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/DJ.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Djibouti",
  },
  {
    country: "Dominica",
    phone_code: "1-767",
    currency: "East Caribbean Dollar",
    currency_bn: "পূর্ব ক্যারিবিয়ান ডলার",
    currency_code: "XCD",
    currency_symbol: "$",
    flag_code: "DM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/DM.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Dominica",
  },
  {
    country: "Dominican Republic",
    phone_code: "1-809",
    currency: "Dominican Peso",
    currency_bn: "ডোমিনিকান পেসো",
    currency_code: "DOP",
    currency_symbol: "$",
    flag_code: "DO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/DO.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Santo_Domingo",
  },
  {
    country: "DR Congo",
    phone_code: "243",
    currency: "Congolese Franc",
    currency_bn: "কঙ্গোলিজ ফ্রাঙ্ক",
    currency_code: "CDF",
    currency_symbol: "Fr",
    flag_code: "CD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CD.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Lubumbashi",
  },
  {
    country: "Ecuador",
    phone_code: "593",
    currency: "United States Dollar",
    currency_bn: "মার্কিন ডলার",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "EC",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/EC.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Guayaquil",
  },
  {
    country: "Egypt",
    phone_code: "20",
    currency: "Egyptian Pound",
    currency_bn: "মিশরীয় পাউন্ড",
    currency_code: "EGP",
    currency_symbol: "£",
    flag_code: "EG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/EG.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Cairo",
  },
  {
    country: "El Salvador",
    phone_code: "503",
    currency: "United States Dollar",
    currency_bn: "মার্কিন ডলার",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "SV",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SV.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/El_Salvador",
  },
  {
    country: "Equatorial Guinea",
    phone_code: "240",
    currency: "Central African CFA Franc",
    currency_bn: "মধ্য আফ্রিকান সিএফএ ফ্রাঙ্ক",
    currency_code: "XAF",
    currency_symbol: "Fr",
    flag_code: "GQ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GQ.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Malabo",
  },
  {
    country: "Eritrea",
    phone_code: "291",
    currency: "Eritrean Nakfa",
    currency_bn: "ইরিত্রিয়ান নাকফা",
    currency_code: "ERN",
    currency_symbol: "Nfk",
    flag_code: "ER",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ER.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Asmara",
  },
  {
    country: "Eswatini",
    phone_code: "268",
    currency: "Swazi Lilangeni",
    currency_bn: "সোয়াজি লিলাঙ্গেনি",
    currency_code: "SZL",
    currency_symbol: "L",
    flag_code: "SZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SZ.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Mbabane",
  },
  {
    country: "Ethiopia",
    phone_code: "251",
    currency: "Ethiopian Birr",
    currency_bn: "ইথিওপিয়ান বির",
    currency_code: "ETB",
    currency_symbol: "Br",
    flag_code: "ET",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ET.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Addis_Ababa",
  },
  {
    country: "Fiji",
    phone_code: "679",
    currency: "Fijian Dollar",
    currency_bn: "ফিজিয়ান ডলার",
    currency_code: "FJD",
    currency_symbol: "$",
    flag_code: "FJ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/FJ.svg",
    timezone: "UTC+12:00",
    named_timezone: "Pacific/Fiji",
  },
  {
    country: "Finland",
    phone_code: "358",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "FI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/FI.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Helsinki",
  },
  {
    country: "France",
    phone_code: "33",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "FR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/FR.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Paris",
  },
  {
    country: "Gabon",
    phone_code: "241",
    currency: "Central African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XAF",
    currency_symbol: "Fr",
    flag_code: "GA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GA.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Libreville",
  },
  {
    country: "Gambia",
    phone_code: "220",
    currency: "Gambian Dalasi",
    currency_code: "GMD",
    currency_symbol: "D",
    flag_code: "GM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GM.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Banjul",
  },
  {
    country: "Georgia",
    phone_code: "995",
    currency: "Georgian Lari",
    currency_bn: "জর্জিয়ান লারি",
    currency_code: "GEL",
    currency_symbol: "₾",
    flag_code: "GE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GE.svg",
    timezone: "UTC+04:00",
    named_timezone: "Asia/Tbilisi",
  },
  {
    country: "Germany",
    phone_code: "49",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "DE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/DE.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Berlin",
  },
  {
    country: "Ghana",
    phone_code: "233",
    currency: "Ghanaian Cedi",
    currency_code: "GHS",
    currency_symbol: "₵",
    flag_code: "GH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GH.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Accra",
  },
  {
    country: "Greece",
    phone_code: "30",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "GR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GR.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Athens",
  },
  {
    country: "Grenada",
    phone_code: "1-473",
    currency: "East Caribbean Dollar",
    currency_code: "XCD",
    currency_symbol: "$",
    flag_code: "GD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GD.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Grenada",
  },
  {
    country: "Guatemala",
    phone_code: "502",
    currency: "Guatemalan Quetzal",
    currency_code: "GTQ",
    currency_symbol: "Q",
    flag_code: "GT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GT.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/Guatemala",
  },
  {
    country: "Guinea",
    phone_code: "224",
    currency: "Guinean Franc",
    currency_code: "GNF",
    currency_symbol: "Fr",
    flag_code: "GN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GN.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Conakry",
  },
  {
    country: "Guinea-Bissau",
    phone_code: "245",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "GW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GW.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Bissau",
  },
  {
    country: "Guyana",
    phone_code: "592",
    currency: "Guyanese Dollar",
    currency_code: "GYD",
    currency_symbol: "$",
    flag_code: "GY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GY.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Guyana",
  },
  {
    country: "Haiti",
    phone_code: "509",
    currency: "Haitian Gourde",
    currency_code: "HTG",
    currency_symbol: "G",
    flag_code: "HT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/HT.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Port-au-Prince",
  },
  {
    country: "Honduras",
    phone_code: "504",
    currency: "Honduran Lempira",
    currency_code: "HNL",
    currency_symbol: "L",
    flag_code: "HN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/HN.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/Tegucigalpa",
  },
  {
    country: "Hungary",
    phone_code: "36",
    currency: "Hungarian Forint",
    currency_bn: "হাঙ্গেরিয়ান ফরিন্ট",
    currency_code: "HUF",
    currency_symbol: "Ft",
    flag_code: "HU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/HU.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Budapest",
  },
  {
    country: "Iceland",
    phone_code: "354",
    currency: "Icelandic Króna",
    currency_bn: "আইসল্যান্ডীয় ক্রোনা",
    currency_code: "ISK",
    currency_symbol: "kr",
    flag_code: "IS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/IS.svg",
    timezone: "UTC+00:00",
    named_timezone: "Atlantic/Reykjavik",
  },
  {
    country: "India",
    phone_code: "91",
    currency: "Indian Rupee",
    currency_bn: "ভারতীয় রুপি",
    currency_code: "INR",
    currency_symbol: "₹",
    flag_code: "IN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/IN.svg",
    timezone: "UTC+05:30",
    named_timezone: "Asia/Kolkata",
  },
  {
    country: "Indonesia",
    phone_code: "62",
    currency: "Indonesian Rupiah",
    currency_bn: "ইন্দোনেশিয়ান রুপিয়াহ",
    currency_code: "IDR",
    currency_symbol: "Rp",
    flag_code: "ID",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ID.svg",
    timezone: "UTC+07:00",
    named_timezone: "Asia/Jakarta",
  },
  {
    country: "Iran",
    phone_code: "98",
    currency: "Iranian Rial",
    currency_bn: "ইরানি রিয়াল",
    currency_code: "IRR",
    currency_symbol: "﷼",
    flag_code: "IR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/IR.svg",
    timezone: "UTC+03:30",
    named_timezone: "Asia/Tehran",
  },
  {
    country: "Iraq",
    phone_code: "964",
    currency: "Iraqi Dinar",
    currency_bn: "ইরাকি দিনার",
    currency_code: "IQD",
    currency_symbol: "ع.د",
    flag_code: "IQ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/IQ.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Baghdad",
  },
  {
    country: "Ireland",
    phone_code: "353",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "IE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/IE.svg",
    timezone: "UTC+00:00",
    named_timezone: "Europe/Dublin",
  },
  {
    country: "Italy",
    phone_code: "39",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "IT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/IT.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Rome",
  },
  {
    country: "Ivory Coast",
    phone_code: "225",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "CI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CI.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Abidjan",
  },
  {
    country: "Jamaica",
    phone_code: "1-876",
    currency: "Jamaican Dollar",
    currency_code: "JMD",
    currency_symbol: "$",
    flag_code: "JM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/JM.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Jamaica",
  },
  {
    country: "Japan",
    phone_code: "81",
    currency: "Japanese Yen",
    currency_bn: "জাপানি ইয়েন",
    currency_code: "JPY",
    currency_symbol: "¥",
    flag_code: "JP",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/JP.svg",
    timezone: "UTC+09:00",
    named_timezone: "Asia/Tokyo",
  },
  {
    country: "Jordan",
    phone_code: "962",
    currency: "Jordanian Dinar",
    currency_bn: "জর্ডানিয়ান দিনার",
    currency_code: "JOD",
    currency_symbol: "د.ا",
    flag_code: "JO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/JO.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Amman",
  },
  {
    country: "Kazakhstan",
    phone_code: "7",
    currency: "Kazakhstani Tenge",
    currency_bn: "কাজাখস্তানি টেঙ্গে",
    currency_code: "KZT",
    currency_symbol: "₸",
    flag_code: "KZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KZ.svg",
    timezone: "UTC+05:00",
    named_timezone: "Asia/Almaty",
  },
  {
    country: "Kenya",
    phone_code: "254",
    currency: "Kenyan Shilling",
    currency_code: "KES",
    currency_symbol: "Sh",
    flag_code: "KE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KE.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Nairobi",
  },
  {
    country: "Kiribati",
    phone_code: "686",
    currency: "Australian Dollar",
    currency_code: "AUD",
    currency_symbol: "$",
    flag_code: "KI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KI.svg",
    timezone: "UTC+12:00",
    named_timezone: "Pacific/Tarawa",
  },
  {
    country: "Kosovo",
    phone_code: "383",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "XK",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/XK.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Belgrade",
  },
  {
    country: "Kuwait",
    phone_code: "965",
    currency: "Kuwaiti Dinar",
    currency_bn: "কুয়েতি দিনার",
    currency_code: "KWD",
    currency_symbol: "د.ك",
    flag_code: "KW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KW.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Kuwait",
  },
  {
    country: "Kyrgyzstan",
    phone_code: "996",
    currency: "Kyrgyzstani Som",
    currency_code: "KGS",
    currency_symbol: "с",
    flag_code: "KG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KG.svg",
    timezone: "UTC+06:00",
    named_timezone: "Asia/Bishkek",
  },
  {
    country: "Laos",
    phone_code: "856",
    currency: "Lao Kip",
    currency_code: "LAK",
    currency_symbol: "₭",
    flag_code: "LA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LA.svg",
    timezone: "UTC+07:00",
    named_timezone: "Asia/Vientiane",
  },
  {
    country: "Latvia",
    phone_code: "371",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "LV",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LV.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Riga",
  },
  {
    country: "Lebanon",
    phone_code: "961",
    currency: "Lebanese Pound",
    currency_bn: "লেবানিজ পাউন্ড",
    currency_code: "LBP",
    currency_symbol: "ل.ل",
    flag_code: "LB",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LB.svg",
    timezone: "UTC+02:00",
    named_timezone: "Asia/Beirut",
  },
  {
    country: "Lesotho",
    phone_code: "266",
    currency: "Lesotho Loti",
    currency_code: "LSL",
    currency_symbol: "L",
    flag_code: "LS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LS.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Maseru",
  },
  {
    country: "Liberia",
    phone_code: "231",
    currency: "Liberian Dollar",
    currency_code: "LRD",
    currency_symbol: "$",
    flag_code: "LR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LR.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Monrovia",
  },
  {
    country: "Libya",
    phone_code: "218",
    currency: "Libyan Dinar",
    currency_bn: "লিবিয়ান দিনার",
    currency_code: "LYD",
    currency_symbol: "ل.د",
    flag_code: "LY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LY.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Tripoli",
  },
  {
    country: "Liechtenstein",
    phone_code: "423",
    currency: "Swiss Franc",
    currency_code: "CHF",
    currency_symbol: "Fr",
    flag_code: "LI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LI.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Vaduz",
  },
  {
    country: "Lithuania",
    phone_code: "370",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "LT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LT.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Vilnius",
  },
  {
    country: "Luxembourg",
    phone_code: "352",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "LU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LU.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Luxembourg",
  },
  {
    country: "Madagascar",
    phone_code: "261",
    currency: "Malagasy Ariary",
    currency_code: "MGA",
    currency_symbol: "Ar",
    flag_code: "MG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MG.svg",
    timezone: "UTC+03:00",
    named_timezone: "Indian/Antananarivo",
  },
  {
    country: "Malawi",
    phone_code: "265",
    currency: "Malawian Kwacha",
    currency_code: "MWK",
    currency_symbol: "MK",
    flag_code: "MW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MW.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Blantyre",
  },
  {
    country: "Malaysia",
    phone_code: "60",
    currency: "Malaysian Ringgit",
    currency_bn: "মালয়েশিয়ান রিঙ্গিত",
    currency_code: "MYR",
    currency_symbol: "RM",
    flag_code: "MY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MY.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Kuala_Lumpur",
  },
  {
    country: "Maldives",
    phone_code: "960",
    currency: "Maldivian Rufiyaa",
    currency_bn: "মালদ্বীপীয় রুফিয়াহ",
    currency_code: "MVR",
    currency_symbol: "Rf",
    flag_code: "MV",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MV.svg",
    timezone: "UTC+05:00",
    named_timezone: "Indian/Maldives",
  },
  {
    country: "Mali",
    phone_code: "223",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "ML",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ML.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Bamako",
  },
  {
    country: "Malta",
    phone_code: "356",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "MT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MT.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Malta",
  },
  {
    country: "Marshall Islands",
    phone_code: "692",
    currency: "United States Dollar",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "MH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MH.svg",
    timezone: "UTC+12:00",
    named_timezone: "Pacific/Majuro",
  },
  {
    country: "Mauritania",
    phone_code: "222",
    currency: "Mauritanian Ouguiya",
    currency_code: "MRU",
    currency_symbol: "UM",
    flag_code: "MR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MR.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Nouakchott",
  },
  {
    country: "Mauritius",
    phone_code: "230",
    currency: "Mauritian Rupee",
    currency_code: "MUR",
    currency_symbol: "₨",
    flag_code: "MU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MU.svg",
    timezone: "UTC+04:00",
    named_timezone: "Indian/Mauritius",
  },
  {
    country: "Mexico",
    phone_code: "52",
    currency: "Mexican Peso",
    currency_bn: "মেক্সিকান পেসো",
    currency_code: "MXN",
    currency_symbol: "$",
    flag_code: "MX",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MX.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/Mexico_City",
  },
  {
    country: "Micronesia",
    phone_code: "691",
    currency: "United States Dollar",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "FM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/FM.svg",
    timezone: "UTC+10:00",
    named_timezone: "Pacific/Chuuk",
  },
  {
    country: "Moldova",
    phone_code: "373",
    currency: "Moldovan Leu",
    currency_code: "MDL",
    currency_symbol: "L",
    flag_code: "MD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MD.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Chisinau",
  },
  {
    country: "Monaco",
    phone_code: "377",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "MC",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MC.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Monaco",
  },
  {
    country: "Mongolia",
    phone_code: "976",
    currency: "Mongolian Tögrög",
    currency_code: "MNT",
    currency_symbol: "₮",
    flag_code: "MN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MN.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Ulaanbaatar",
  },
  {
    country: "Montenegro",
    phone_code: "382",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "ME",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ME.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Podgorica",
  },
  {
    country: "Morocco",
    phone_code: "212",
    currency: "Moroccan Dirham",
    currency_code: "MAD",
    currency_symbol: "د.م.",
    flag_code: "MA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MA.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Casablanca",
  },
  {
    country: "Mozambique",
    phone_code: "258",
    currency: "Mozambican Metical",
    currency_code: "MZN",
    currency_symbol: "MT",
    flag_code: "MZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MZ.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Maputo",
  },
  {
    country: "Myanmar",
    phone_code: "95",
    currency: "Myanmar Kyat",
    currency_bn: "মিয়ানমার কিয়াত",
    currency_code: "MMK",
    currency_symbol: "K",
    flag_code: "MM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MM.svg",
    timezone: "UTC+06:30",
    named_timezone: "Asia/Yangon",
  },
  {
    country: "Namibia",
    phone_code: "264",
    currency: "Namibian Dollar",
    currency_code: "NAD",
    currency_symbol: "$",
    flag_code: "NA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NA.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Windhoek",
  },
  {
    country: "Nauru",
    phone_code: "674",
    currency: "Australian Dollar",
    currency_code: "AUD",
    currency_symbol: "$",
    flag_code: "NR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NR.svg",
    timezone: "UTC+12:00",
    named_timezone: "Pacific/Nauru",
  },
  {
    country: "Nepal",
    phone_code: "977",
    currency: "Nepalese Rupee",
    currency_bn: "নেপালি রুপি",
    currency_code: "NPR",
    currency_symbol: "₨",
    flag_code: "NP",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NP.svg",
    timezone: "UTC+05:45",
    named_timezone: "Asia/Kathmandu",
  },
  {
    country: "Netherlands",
    phone_code: "31",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "NL",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NL.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Amsterdam",
  },
  {
    country: "New Zealand",
    phone_code: "64",
    currency: "New Zealand Dollar",
    currency_bn: "নিউজিল্যান্ড ডলার",
    currency_code: "NZD",
    currency_symbol: "$",
    flag_code: "NZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NZ.svg",
    timezone: "UTC+12:00",
    named_timezone: "Pacific/Auckland",
  },
  {
    country: "Nicaragua",
    phone_code: "505",
    currency: "Nicaraguan Córdoba",
    currency_code: "NIO",
    currency_symbol: "C$",
    flag_code: "NI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NI.svg",
    timezone: "UTC−06:00",
    named_timezone: "America/Managua",
  },
  {
    country: "Niger",
    phone_code: "227",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "NE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NE.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Niamey",
  },
  {
    country: "Nigeria",
    phone_code: "234",
    currency: "Nigerian Naira",
    currency_code: "NGN",
    currency_symbol: "₦",
    flag_code: "NG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NG.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Lagos",
  },
  {
    country: "North Korea",
    phone_code: "850",
    currency: "North Korean Won",
    currency_code: "KPW",
    currency_symbol: "₩",
    flag_code: "KP",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KP.svg",
    timezone: "UTC+09:00",
    named_timezone: "Asia/Pyongyang",
  },
  {
    country: "North Macedonia",
    phone_code: "389",
    currency: "Macedonian Denar",
    currency_code: "MKD",
    currency_symbol: "ден",
    flag_code: "MK",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/MK.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Skopje",
  },
  {
    country: "Norway",
    phone_code: "47",
    currency: "Norwegian Krone",
    currency_bn: "নরওয়েজিয়ান ক্রোন",
    currency_code: "NOK",
    currency_symbol: "kr",
    flag_code: "NO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/NO.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Oslo",
  },
  {
    country: "Oman",
    phone_code: "968",
    currency: "Omani Rial",
    currency_bn: "ওমানি রিয়াল",
    currency_code: "OMR",
    currency_symbol: "ر.ع.",
    flag_code: "OM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/OM.svg",
    timezone: "UTC+04:00",
    named_timezone: "Asia/Muscat",
  },
  {
    country: "Pakistan",
    phone_code: "92",
    currency: "Pakistani Rupee",
    currency_bn: "পাকিস্তানি রুপি",
    currency_code: "PKR",
    currency_symbol: "₨",
    flag_code: "PK",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PK.svg",
    timezone: "UTC+05:00",
    named_timezone: "Asia/Karachi",
  },
  {
    country: "Palau",
    phone_code: "680",
    currency: "United States Dollar",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "PW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PW.svg",
    timezone: "UTC+09:00",
    named_timezone: "Pacific/Palau",
  },
  {
    country: "Palestine",
    phone_code: "970",
    currency: "New Shekel",
    currency_code: "ILS",
    currency_symbol: "₪",
    flag_code: "PS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PS.svg",
    timezone: "UTC+02:00",
    named_timezone: "Asia/Hebron",
  },
  {
    country: "Panama",
    phone_code: "507",
    currency: "Panamanian Balboa",
    currency_code: "PAB",
    currency_symbol: "B/.",
    flag_code: "PA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PA.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Panama",
  },
  {
    country: "Papua New Guinea",
    phone_code: "675",
    currency: "Papua New Guinean Kina",
    currency_code: "PGK",
    currency_symbol: "K",
    flag_code: "PG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PG.svg",
    timezone: "UTC+10:00",
    named_timezone: "Pacific/Port_Moresby",
  },
  {
    country: "Paraguay",
    phone_code: "595",
    currency: "Paraguayan Guaraní",
    currency_code: "PYG",
    currency_symbol: "₲",
    flag_code: "PY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PY.svg",
    timezone: "UTC−03:00",
    named_timezone: "America/Asuncion",
  },
  {
    country: "Peru",
    phone_code: "51",
    currency: "Peruvian Sol",
    currency_code: "PEN",
    currency_symbol: "S/",
    flag_code: "PE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PE.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/Lima",
  },
  {
    country: "Philippines",
    phone_code: "63",
    currency: "Philippine Peso",
    currency_bn: "ফিলিপাইন পেসো",
    currency_code: "PHP",
    currency_symbol: "₱",
    flag_code: "PH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PH.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Manila",
  },
  {
    country: "Poland",
    phone_code: "48",
    currency: "Polish Złoty",
    currency_code: "PLN",
    currency_symbol: "zł",
    flag_code: "PL",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PL.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Warsaw",
  },
  {
    country: "Portugal",
    phone_code: "351",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "PT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/PT.svg",
    timezone: "UTC+00:00",
    named_timezone: "Europe/Lisbon",
  },
  {
    country: "Qatar",
    phone_code: "974",
    currency: "Qatari Riyal",
    currency_bn: "কাতারি রিয়াল",
    currency_code: "QAR",
    currency_symbol: "ر.ق",
    flag_code: "QA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/QA.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Qatar",
  },
  {
    country: "Romania",
    phone_code: "40",
    currency: "Romanian Leu",
    currency_code: "RON",
    currency_symbol: "lei",
    flag_code: "RO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/RO.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Bucharest",
  },
  {
    country: "Russia",
    phone_code: "7",
    currency: "Russian Ruble",
    currency_bn: "রাশিয়ান রুবেল",
    currency_code: "RUB",
    currency_symbol: "₽",
    flag_code: "RU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/RU.svg",
    timezone: "UTC+03:00",
    named_timezone: "Europe/Moscow",
  },
  {
    country: "Rwanda",
    phone_code: "250",
    currency: "Rwandan Franc",
    currency_code: "RWF",
    currency_symbol: "Fr",
    flag_code: "RW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/RW.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Kigali",
  },
  {
    country: "Saint Kitts and Nevis",
    phone_code: "1-869",
    currency: "East Caribbean Dollar",
    currency_code: "XCD",
    currency_symbol: "$",
    flag_code: "KN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KN.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/St_Kitts",
  },
  {
    country: "Saint Lucia",
    phone_code: "1-758",
    currency: "East Caribbean Dollar",
    currency_code: "XCD",
    currency_symbol: "$",
    flag_code: "LC",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LC.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/St_Lucia",
  },
  {
    country: "Saint Vincent and the Grenadines",
    phone_code: "1-784",
    currency: "East Caribbean Dollar",
    currency_code: "XCD",
    currency_symbol: "$",
    flag_code: "VC",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/VC.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/St_Vincent",
  },
  {
    country: "Samoa",
    phone_code: "685",
    currency: "Samoan Tālā",
    currency_code: "WST",
    currency_symbol: "T",
    flag_code: "WS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/WS.svg",
    timezone: "UTC+13:00",
    named_timezone: "Pacific/Apia",
  },
  {
    country: "San Marino",
    phone_code: "378",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "SM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SM.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/San_Marino",
  },
  {
    country: "Sao Tome and Principe",
    phone_code: "239",
    currency: "São Tomé and Príncipe Dobra",
    currency_code: "STN",
    currency_symbol: "Db",
    flag_code: "ST",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ST.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Sao_Tome",
  },
  {
    country: "Saudi Arabia",
    phone_code: "966",
    currency: "Saudi Riyal",
    currency_bn: "সৌদি রিয়াল",
    currency_code: "SAR",
    currency_symbol: "ر.س",
    flag_code: "SA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SA.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Riyadh",
  },
  {
    country: "Senegal",
    phone_code: "221",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "SN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SN.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Dakar",
  },
  {
    country: "Serbia",
    phone_code: "381",
    currency: "Serbian Dinar",
    currency_code: "RSD",
    currency_symbol: "дин",
    flag_code: "RS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/RS.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Belgrade",
  },
  {
    country: "Seychelles",
    phone_code: "248",
    currency: "Seychellois Rupee",
    currency_code: "SCR",
    currency_symbol: "₨",
    flag_code: "SC",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SC.svg",
    timezone: "UTC+04:00",
    named_timezone: "Indian/Mahe",
  },
  {
    country: "Sierra Leone",
    phone_code: "232",
    currency: "Sierra Leonean Leone",
    currency_code: "SLL",
    currency_symbol: "Le",
    flag_code: "SL",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SL.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Freetown",
  },
  {
    country: "Singapore",
    phone_code: "65",
    currency: "Singapore Dollar",
    currency_bn: "সিঙ্গাপুর ডলার",
    currency_code: "SGD",
    currency_symbol: "$",
    flag_code: "SG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SG.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Singapore",
  },
  {
    country: "Slovakia",
    phone_code: "421",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "SK",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SK.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Bratislava",
  },
  {
    country: "Slovenia",
    phone_code: "386",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "SI",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SI.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Ljubljana",
  },
  {
    country: "Solomon Islands",
    phone_code: "677",
    currency: "Solomon Islands Dollar",
    currency_code: "SBD",
    currency_symbol: "$",
    flag_code: "SB",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SB.svg",
    timezone: "UTC+11:00",
    named_timezone: "Pacific/Guadalcanal",
  },
  {
    country: "Somalia",
    phone_code: "252",
    currency: "Somali Shilling",
    currency_code: "SOS",
    currency_symbol: "Sh",
    flag_code: "SO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SO.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Mogadishu",
  },
  {
    country: "South Africa",
    phone_code: "27",
    currency: "South African Rand",
    currency_bn: "দক্ষিণ আফ্রিকান র্যান্ড",
    currency_code: "ZAR",
    currency_symbol: "R",
    flag_code: "ZA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ZA.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Johannesburg",
  },
  {
    country: "South Korea",
    phone_code: "82",
    currency: "South Korean Won",
    currency_bn: "দক্ষিণ কোরিয়ান ওয়ন",
    currency_code: "KRW",
    currency_symbol: "₩",
    flag_code: "KR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/KR.svg",
    timezone: "UTC+09:00",
    named_timezone: "Asia/Seoul",
  },
  {
    country: "South Sudan",
    phone_code: "211",
    currency: "South Sudanese Pound",
    currency_code: "SSP",
    currency_symbol: "£",
    flag_code: "SS",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SS.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Juba",
  },
  {
    country: "Spain",
    phone_code: "34",
    currency: "Euro",
    currency_bn: "ইউরো",
    currency_code: "EUR",
    currency_symbol: "€",
    flag_code: "ES",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ES.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Madrid",
  },
  {
    country: "Sri Lanka",
    phone_code: "94",
    currency: "Sri Lankan Rupee",
    currency_bn: "শ্রীলঙ্কান রুপি",
    currency_code: "LKR",
    currency_symbol: "₨",
    flag_code: "LK",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/LK.svg",
    timezone: "UTC+05:30",
    named_timezone: "Asia/Colombo",
  },
  {
    country: "Sudan",
    phone_code: "249",
    currency: "Sudanese Pound",
    currency_code: "SDG",
    currency_symbol: "£",
    flag_code: "SD",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SD.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Khartoum",
  },
  {
    country: "Suriname",
    phone_code: "597",
    currency: "Surinamese Dollar",
    currency_code: "SRD",
    currency_symbol: "$",
    flag_code: "SR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SR.svg",
    timezone: "UTC−03:00",
    named_timezone: "America/Paramaribo",
  },
  {
    country: "Sweden",
    phone_code: "46",
    currency: "Swedish Krona",
    currency_bn: "সুইডিশ ক্রোনা",
    currency_code: "SEK",
    currency_symbol: "kr",
    flag_code: "SE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SE.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Stockholm",
  },
  {
    country: "Switzerland",
    phone_code: "41",
    currency: "Swiss Franc",
    currency_bn: "সুইস ফ্রাঙ্ক",
    currency_code: "CHF",
    currency_symbol: "Fr",
    flag_code: "CH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/CH.svg",
    timezone: "UTC+01:00",
    named_timezone: "Europe/Zurich",
  },
  {
    country: "Syria",
    phone_code: "963",
    currency: "Syrian Pound",
    currency_code: "SYP",
    currency_symbol: "£",
    flag_code: "SY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/SY.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Damascus",
  },
  {
    country: "Taiwan",
    phone_code: "886",
    currency: "New Taiwan Dollar",
    currency_code: "TWD",
    currency_symbol: "$",
    flag_code: "TW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TW.svg",
    timezone: "UTC+08:00",
    named_timezone: "Asia/Taipei",
  },
  {
    country: "Tajikistan",
    phone_code: "992",
    currency: "Tajikistani Somoni",
    currency_code: "TJS",
    currency_symbol: "SM",
    flag_code: "TJ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TJ.svg",
    timezone: "UTC+05:00",
    named_timezone: "Asia/Dushanbe",
  },
  {
    country: "Tanzania",
    phone_code: "255",
    currency: "Tanzanian Shilling",
    currency_code: "TZS",
    currency_symbol: "Sh",
    flag_code: "TZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TZ.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Dar_es_Salaam",
  },
  {
    country: "Thailand",
    phone_code: "66",
    currency: "Thai Baht",
    currency_bn: "থাই বাহত",
    currency_code: "THB",
    currency_symbol: "฿",
    flag_code: "TH",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TH.svg",
    timezone: "UTC+07:00",
    named_timezone: "Asia/Bangkok",
  },
  {
    country: "Timor-Leste",
    phone_code: "670",
    currency: "United States Dollar",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "TL",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TL.svg",
    timezone: "UTC+09:00",
    named_timezone: "Asia/Dili",
  },
  {
    country: "Togo",
    phone_code: "228",
    currency: "West African CFA Franc",
    currency_bn: "সিএফএ ফ্রাঙ্ক",
    currency_code: "XOF",
    currency_symbol: "Fr",
    flag_code: "TG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TG.svg",
    timezone: "UTC+00:00",
    named_timezone: "Africa/Lome",
  },
  {
    country: "Tonga",
    phone_code: "676",
    currency: "Tongan Paʻanga",
    currency_code: "TOP",
    currency_symbol: "T$",
    flag_code: "TO",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TO.svg",
    timezone: "UTC+13:00",
    named_timezone: "Pacific/Tongatapu",
  },
  {
    country: "Trinidad and Tobago",
    phone_code: "1-868",
    currency: "Trinidad and Tobago Dollar",
    currency_code: "TTD",
    currency_symbol: "$",
    flag_code: "TT",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TT.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Port_of_Spain",
  },
  {
    country: "Tunisia",
    phone_code: "216",
    currency: "Tunisian Dinar",
    currency_code: "TND",
    currency_symbol: "د.ت",
    flag_code: "TN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TN.svg",
    timezone: "UTC+01:00",
    named_timezone: "Africa/Tunis",
  },
  {
    country: "Turkey",
    phone_code: "90",
    currency: "Turkish Lira",
    currency_bn: "তুর্কি লিরা",
    currency_code: "TRY",
    currency_symbol: "₺",
    flag_code: "TR",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TR.svg",
    timezone: "UTC+03:00",
    named_timezone: "Europe/Istanbul",
  },
  {
    country: "Turkmenistan",
    phone_code: "993",
    currency: "Turkmenistani Manat",
    currency_code: "TMT",
    currency_symbol: "m",
    flag_code: "TM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TM.svg",
    timezone: "UTC+05:00",
    named_timezone: "Asia/Ashgabat",
  },
  {
    country: "Tuvalu",
    phone_code: "688",
    currency: "Australian Dollar",
    currency_code: "AUD",
    currency_symbol: "$",
    flag_code: "TV",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/TV.svg",
    timezone: "UTC+12:00",
    named_timezone: "Pacific/Funafuti",
  },
  {
    country: "Uganda",
    phone_code: "256",
    currency: "Ugandan Shilling",
    currency_code: "UGX",
    currency_symbol: "Sh",
    flag_code: "UG",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/UG.svg",
    timezone: "UTC+03:00",
    named_timezone: "Africa/Kampala",
  },
  {
    country: "Ukraine",
    phone_code: "380",
    currency: "Ukrainian Hryvnia",
    currency_code: "UAH",
    currency_symbol: "₴",
    flag_code: "UA",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/UA.svg",
    timezone: "UTC+02:00",
    named_timezone: "Europe/Kyiv",
  },
  {
    country: "United Arab Emirates",
    phone_code: "971",
    currency: "United Arab Emirates Dirham",
    currency_bn: "সংযুক্ত আরব আমিরাত দিরহাম",
    currency_code: "AED",
    currency_symbol: "د.إ",
    flag_code: "AE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/AE.svg",
    timezone: "UTC+04:00",
    named_timezone: "Asia/Dubai",
  },
  {
    country: "United Kingdom",
    phone_code: "44",
    currency: "British Pound",
    currency_bn: "ব্রিটিশ পাউন্ড",
    currency_code: "GBP",
    currency_symbol: "£",
    flag_code: "GB",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/GB.svg",
    timezone: "UTC+00:00",
    named_timezone: "Europe/London",
  },
  {
    country: "United States",
    phone_code: "1",
    currency: "United States Dollar",
    currency_bn: "মার্কিন ডলার",
    currency_code: "USD",
    currency_symbol: "$",
    flag_code: "US",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/US.svg",
    timezone: "UTC−05:00",
    named_timezone: "America/New_York",
  },
  {
    country: "Uruguay",
    phone_code: "598",
    currency: "Uruguayan Peso",
    currency_code: "UYU",
    currency_symbol: "$",
    flag_code: "UY",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/UY.svg",
    timezone: "UTC−03:00",
    named_timezone: "America/Montevideo",
  },
  {
    country: "Uzbekistan",
    phone_code: "998",
    currency: "Uzbekistani Som",
    currency_code: "UZS",
    currency_symbol: "сўм",
    flag_code: "UZ",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/UZ.svg",
    timezone: "UTC+05:00",
    named_timezone: "Asia/Tashkent",
  },
  {
    country: "Vanuatu",
    phone_code: "678",
    currency: "Vanuatu Vatu",
    currency_code: "VUV",
    currency_symbol: "VT",
    flag_code: "VU",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/VU.svg",
    timezone: "UTC+11:00",
    named_timezone: "Pacific/Efate",
  },
  {
    country: "Venezuela",
    phone_code: "58",
    currency: "Venezuelan Bolívar",
    currency_code: "VES",
    currency_symbol: "Bs",
    flag_code: "VE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/VE.svg",
    timezone: "UTC−04:00",
    named_timezone: "America/Caracas",
  },
  {
    country: "Vietnam",
    phone_code: "84",
    currency: "Vietnamese Đồng",
    currency_bn: "ভিয়েতনামি ডং",
    currency_code: "VND",
    currency_symbol: "₫",
    flag_code: "VN",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/VN.svg",
    timezone: "UTC+07:00",
    named_timezone: "Asia/Ho_Chi_Minh",
  },
  {
    country: "Yemen",
    phone_code: "967",
    currency: "Yemeni Rial",
    currency_code: "YER",
    currency_symbol: "﷼",
    flag_code: "YE",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/YE.svg",
    timezone: "UTC+03:00",
    named_timezone: "Asia/Aden",
  },
  {
    country: "Zambia",
    phone_code: "260",
    currency: "Zambian Kwacha",
    currency_code: "ZMW",
    currency_symbol: "ZK",
    flag_code: "ZM",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ZM.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Lusaka",
  },
  {
    country: "Zimbabwe",
    phone_code: "263",
    currency: "Zimbabwean Dollar",
    currency_code: "ZWL",
    currency_symbol: "$",
    flag_code: "ZW",
    flag_url:
      "https://purecatamphetamine.github.io/country-flag-icons/3x2/ZW.svg",
    timezone: "UTC+02:00",
    named_timezone: "Africa/Harare",
  },
];
